/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.victorjuly.cursosonline.view;

import com.victorjuly.cursosonline.controller.Controller;
import com.victorjuly.cursosonline.controller.CourseController;
import com.victorjuly.cursosonline.exception.EmptyStringException;
import com.victorjuly.cursosonline.exception.NegativeNumberException;
import com.victorjuly.cursosonline.model.Course;

import javax.swing.JOptionPane;

public class CourseRegisterView extends javax.swing.JFrame {

    /**
     * Creates new form CourseRegisterView
     */
    public CourseRegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCoursePrice = new javax.swing.JTextField();
        lblCourseTeacher = new javax.swing.JLabel();
        txtCourseTeacher = new javax.swing.JTextField();
        comboBoxCourseCategory = new javax.swing.JComboBox<>();
        lblCourseName = new javax.swing.JLabel();
        lblCourseCategory = new javax.swing.JLabel();
        lblCourseTime = new javax.swing.JLabel();
        lblCourseDescription = new javax.swing.JLabel();
        btnCostumerFinalRegister = new javax.swing.JButton();
        txtCourseDescription = new javax.swing.JTextField();
        txtCourseTime = new javax.swing.JTextField();
        btnCourseRegisterBack = new javax.swing.JButton();
        txtCourseName = new javax.swing.JTextField();
        lblCoursePrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCourseTeacher.setText("Professor:");

        comboBoxCourseCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCourseName.setText("Nome:");

        lblCourseCategory.setText("Categoria:");

        lblCourseTime.setText("Duração:");

        lblCourseDescription.setText("Descrição:");

        btnCostumerFinalRegister.setText("Cadastrar");
        btnCostumerFinalRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCostumerFinalRegisterActionPerformed(evt);
            }
        });

        btnCourseRegisterBack.setText("Voltar");
        btnCourseRegisterBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseRegisterBackActionPerformed(evt);
            }
        });

        lblCoursePrice.setText("Preço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnCourseRegisterBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCourseTime)
                                .addGap(18, 18, 18)
                                .addComponent(txtCourseTime, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCourseCategory)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxCourseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCourseTeacher)
                                .addGap(18, 18, 18)
                                .addComponent(txtCourseTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCourseName)
                                .addGap(18, 18, 18)
                                .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCoursePrice)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCoursePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCourseDescription)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCostumerFinalRegister)
                                        .addComponent(txtCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnCourseRegisterBack)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseTeacher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCourseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCoursePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCoursePrice))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCostumerFinalRegister)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCostumerFinalRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCostumerFinalRegisterActionPerformed
        try {

            if(comboBoxCourseCategory.getSelectedIndex() == -1) {
                throw new IllegalArgumentException("Selecione a categoria do curso");
            }

            String name = txtCourseName.getText();
            String teacher = txtCourseTeacher.getText();
            int time = Integer.parseInt(txtCourseTime.getText());
            String category = (String) comboBoxCourseCategory.getSelectedItem();
            double price = Double.parseDouble(txtCoursePrice.getText());
            String description = txtCourseDescription.getText();

            Course course = new Course(name, price, teacher, time, description, Course.Category.valueOf(category));

            if (name.equals("")) {
                txtCourseName.requestFocus();
                throw new EmptyStringException("Titulo não pode ser vazio");
            }
            if (time < 0) {
                txtCourseTime.requestFocus();
                throw new NegativeNumberException("Duração não pode ser negativa");
            }
            if (price < 0) {
                txtCoursePrice.requestFocus();
                throw new NegativeNumberException("Preço não pode ser negativa");
            }

            Controller.get(CourseController.class).store(course);
            JOptionPane.showMessageDialog(null, "Curso cadastrado com sucesso");
            txtCourseName.requestFocus();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "A duração e o preço precisam ser números");
        } catch(RuntimeException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnCostumerFinalRegisterActionPerformed

    private void btnCourseRegisterBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseRegisterBackActionPerformed
        HomeView frame = new HomeView();
        frame.setVisible(true);
    }//GEN-LAST:event_btnCourseRegisterBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseRegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCostumerFinalRegister;
    private javax.swing.JButton btnCourseRegisterBack;
    private javax.swing.JComboBox<String> comboBoxCourseCategory;
    private javax.swing.JLabel lblCourseCategory;
    private javax.swing.JLabel lblCourseDescription;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCoursePrice;
    private javax.swing.JLabel lblCourseTeacher;
    private javax.swing.JLabel lblCourseTime;
    private javax.swing.JTextField txtCourseDescription;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCoursePrice;
    private javax.swing.JTextField txtCourseTeacher;
    private javax.swing.JTextField txtCourseTime;
    // End of variables declaration//GEN-END:variables
}
